In [3]:
import numpy as np

# numpy 기초
a = np.array([0,1,2,3,4,5], dtype="uint8") # 1차원 배열
b = np.array([(0,1,2), (3,4,5)], dtype="uint8") # 2차원 배열 2x3
c = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]], dtype="uint8") # 3차원 배열 2x2x3

print("a: ", a)
print("type(a): ", type(a))
print("b: ", b)
print("c: ", c)

print(len(c)) # 3차원 배열 깊이
print(len(c[0])) # 3차원 배열 행
print(len(c[0][0])) # 3차원 배열 열

a:  [0 1 2 3 4 5]
type(a):  <class 'numpy.ndarray'>
b:  [[0 1 2]
 [3 4 5]]
c:  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
2
2
3


In [39]:
# 배열 속성알아보기
print(a.ndim) #  배열 차원수 또는 배열의 축수
print(a.shape) # 배열 각 차원 크기 표현
print(a.dtype) # 배열 요소의 데이터 타입

print(b.ndim)
print(b.shape)

print(c.ndim)
print(c.shape)

1
(6,)
uint8
2
(2, 3)
3
(2, 2, 3)


In [5]:
# 배열 모양새
print(a.size) # 전체 배열 요소 수
print(b.size)
print(c.size)

6
6
12


In [40]:
# 배열의 전치
print(a.T) # 전치, 동일한 결과
print(b.T) # 전치, 행과 열이 뒤바뀜

[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]


In [7]:
c.transpose(0,2,1) #첫번째 차원은 그대로 두고, 두번째, 세번째 축을 변경

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]], dtype=uint8)

In [8]:
c.swapaxes(0,1) #세번째 차원은 그대로 두고, 첫번째, 두번째 축을 변경

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]], dtype=uint8)

In [97]:
# 배열 인덱싱
print(b[0, 1]) # b 2차원 배열의 첫번째 행의 두번째 열
print(b[1, 2]) # b 2차원 배열의 두번째 행의 세번째 열
print(c[0,1,1]) # c 3차원 배열의 첫번째 차원의 두번째 행, 두번째 열

1
5
4


In [98]:
# 배열 슬라이싱
print(c[0, :2, :2]) # c 3차원 배열의 첫번째 차원에서 두번째 행까지의 두번째 열까지

[[0 1]
 [3 4]]


In [99]:
print(b)
# 배열을 모양을 변경
b.reshape(3,2)

[[0 1 2]
 [3 4 5]]


array([[0, 1],
       [2, 3],
       [4, 5]], dtype=uint8)

In [100]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=uint8)

## fancy indexing

In [101]:
import numpy as np

fancy_arr = np.arange(3*3*2, dtype="uint8")
fancy_arr = fancy_arr.reshape(3,2,3)
fancy_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]], dtype=uint8)

In [102]:
fancy_arr.dtype

dtype('uint8')

In [103]:
# fancy indexing
# 1차원의 첫번째 요소에서 두번째 배열
fancy_arr[[0],[1]]

array([[3, 4, 5]], dtype=uint8)

In [104]:
fancy_arr[[0],[1],[2,1,0]]

array([5, 4, 3], dtype=uint8)

In [105]:
fancy_arr[[-1],[0],[2,1,0]]

array([14, 13, 12], dtype=uint8)

##  배열 합치기 및 나누기

In [106]:
# 배열 함치기
np.concatenate([b,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]], dtype=uint8)

In [107]:
# 배열 함치기(열기준)
np.concatenate([b,b], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]], dtype=uint8)

In [108]:
a1 = np.array([(0,1,2,3), (4,5,6,7)] , dtype="uint8") # 2차원 배열
b1 = np.array([(10,11,12,13), (14,15,16,17)] , dtype="uint8") # 2차원 배열

# 행기준으로 합치기
np.vstack((a1,b1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [10, 11, 12, 13],
       [14, 15, 16, 17]], dtype=uint8)

In [109]:
# 열기준으로 합치기
np.hstack((a1,b1))

array([[ 0,  1,  2,  3, 10, 11, 12, 13],
       [ 4,  5,  6,  7, 14, 15, 16, 17]], dtype=uint8)

In [110]:
b2 = np.array([(0,1,2,3), (4,5,6,7)] , dtype="uint8") # 2차원 배열

# 행기준으로 2부분 나누기
np.split(b2,2)

[array([[0, 1, 2, 3]], dtype=uint8), array([[4, 5, 6, 7]], dtype=uint8)]

In [111]:
# 행기준으로 2부분 나누기
np.vsplit(b2,2)

[array([[0, 1, 2, 3]], dtype=uint8), array([[4, 5, 6, 7]], dtype=uint8)]

In [112]:
#열기준 2부분 나누기
np.split(b2,2, axis=1)

[array([[0, 1],
        [4, 5]], dtype=uint8),
 array([[2, 3],
        [6, 7]], dtype=uint8)]

In [113]:
#열기준 2부분 나누기
np.hsplit(b2,2)

[array([[0, 1],
        [4, 5]], dtype=uint8),
 array([[2, 3],
        [6, 7]], dtype=uint8)]

In [114]:
# 배열 생성 함수를 활용한 배열 만들기
z1 = np.zeros(3) # '0' 3개 요소 1차원 배열
z2 = np.zeros((3,3)) # '0' 3x3개 요소 2차원 배열 
one1 = np.ones(3)  # '1' 3개 요소 1차원 배열
one2 = np.ones((3,3)) # '1' 3x3개 요소 2차원 배열 

print("zero1: ", z1)
print("zero2: ", z2)
print("one1: ", one1)
print("one2: ", one2)

# '0'부터 '6'미만까지 '1'씩 증가하는 1차원 수열 
#(빌트인 함수 range와 유사)
ar1 = np.arange(0, 6, 1, dtype=np.int8)
print("arange " , ar1)

lin1 = np.linspace(1, 2, 3)

#초기화되지 않은 값으로 배열을 생성
print("empty(5): ", np.empty(5))
e1 = np.empty((2,3))

# 4x4 단위행렬 만들기
e2 = np.eye(4)

# 2x3배열을 만드록, 20 값으로 모두 채움
f1 = np.full((2,3),20)

# 표준정규분포 난수
ran1 = np.random.rand(2,3)
# 가우시안 표준정규분포 난수
ran2 = np.random.randn(2,3)




print("linspace: " , lin1)
print("empty: " , e1)
print("eye: " , e2)
print("full: ", f1)
print("random1: ", ran1)
print("random2: ", ran2)

zero1:  [0. 0. 0.]
zero2:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
one1:  [1. 1. 1.]
one2:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arange  [0 1 2 3 4 5]
empty(5):  [4.94065646e-324 8.83060065e-312 8.83060065e-312 8.83060065e-312
 3.56175136e-317]
linspace:  [1.  1.5 2. ]
empty:  [[3.18963003 0.02518802 0.2264934 ]
 [4.13477322 0.06954297 0.01006749]]
eye:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
full:  [[20 20 20]
 [20 20 20]]
random1:  [[0.7169401  0.62893829 0.70199129]
 [0.74700353 0.94739268 0.01265234]]
random2:  [[-0.4852035  -0.0369702   0.56050706]
 [ 1.20421013 -0.75117658  0.67506158]]


## 배열 산술

In [115]:
# 배열 산술

arr1 = np.random.rand(2,3)
arr1


array([[0.82903317, 0.91345669, 0.43502814],
       [0.84441527, 0.51339248, 0.42810704]])

In [116]:
arr2 = np.random.randn(2,3)
arr2

array([[ 0.11135704, -1.43272376,  0.20529112],
       [-1.01409101, -0.09815295, -0.86271755]])

In [117]:
arr3 = arr1 * arr2
arr3

array([[ 0.09231868, -1.30873111,  0.08930741],
       [-0.85631393, -0.05039099, -0.36933546]])

In [118]:
arr4 = np.ones((2,3)) * 2 # 모든 요소를 2로 곱함
arr4

array([[2., 2., 2.],
       [2., 2., 2.]])

In [119]:
arr2 ** 2 # 모든 요소 2로 거듭제곱

array([[0.01240039, 2.05269739, 0.04214444],
       [1.02838057, 0.009634  , 0.74428158]])

In [120]:
# 조건
arr2[ arr2 > 1]

array([], dtype=float64)

In [121]:
np.where( arr2 > 1)

(array([], dtype=int64), array([], dtype=int64))

In [122]:
np.where( arr2 > 1, 'Yes', arr1)

array([['0.8290331713411739', '0.9134566904226', '0.43502814040073845'],
       ['0.8444152705962727', '0.5133924808583554',
        '0.42810704340661987']], dtype='<U32')

In [123]:
# 배열 크기 변형

In [124]:
# 배열 연결

In [125]:
# 통계

In [126]:
# 난수