In [1]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
c = a + 2
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
a_dash = np.array([[2,2,2],[2,2,2],[2,2,2]])
e = a + a_dash # a + 2와 같다 (브로드캐스팅을 적극 활용하자)
e

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
b = np.array([0,1,2])
b


array([0, 1, 2])

In [8]:
c = a + b
c

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [9]:
a[1]

array([3, 4, 5])