In [14]:
import numpy as np
x = np.arange(1,7).reshape((2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
y = np.arange(1,4)
y

array([1, 2, 3])

In [16]:
#add
x+y

array([[2, 4, 6],
       [5, 7, 9]])

In [17]:
#subtract
np.subtract(x,y)

array([[0, 0, 0],
       [3, 3, 3]])

In [18]:
x + np.positive(x)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [19]:
x + np.negative(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
# 곱하기
np.multiply(x,y)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [21]:
#나누기
np.divide(x, y)

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [22]:
#나눈 몫
np.floor_divide(x,y)

array([[1, 1, 1],
       [4, 2, 2]])

In [23]:
#x1요소의  x2요소 제곱
np.power(x,y)

array([[  1,   4,  27],
       [  4,  25, 216]])

In [24]:
#x1요소을 x2요소로 나눈 나머지
np.mod(x,y)

array([[0, 0, 0],
       [0, 1, 0]])

In [26]:
#x요소와 y요소의 최대공약수
np.gcd(x,y)

array([[1, 2, 3],
       [1, 1, 3]])

In [27]:
#x요소과 y 요소별 최대값. fmax는 NaN를 무시함
np.maximum([[1,2,3],[4,5,np.nan]], y)

array([[ 1.,  2.,  3.],
       [ 4.,  5., nan]])

In [28]:
np.fmax([[1,2,3],[4,5,np.nan]], y)

array([[1., 2., 3.],
       [4., 5., 3.]])

In [29]:
#x요소과 y 요소별 최소값. fmin은 NaN를 무시함
np.minimum([[1,2,3],[4,5,np.nan]], y)

array([[ 1.,  2.,  3.],
       [ 1.,  2., nan]])

In [30]:
np.fmin([[1,2,3],[4,5,np.nan]],y)

array([[1., 2., 3.],
       [1., 2., 3.]])

In [31]:
#x요소가 y요소보다 큰지 불리언 값 반환
np.greater(x,y)

array([[False, False, False],
       [ True,  True,  True]])

In [32]:
#x요소가 y요소보다 크거나 같은지 불리언값 반환
np.greater_equal(x,y)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [33]:
x >= y

array([[ True,  True,  True],
       [ True,  True,  True]])

In [34]:
#x요소가 y요소보다 작음
np.less(x,y)

array([[False, False, False],
       [False, False, False]])

In [35]:
x < y

array([[False, False, False],
       [False, False, False]])

In [36]:
#x요소가 y요소보다 작거나 같은지 불리언값 반환
np.less_equal(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [38]:
#x요소가 y요소와 같은지 불리언값 반환
np.equal(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [39]:
# x요소가 y요소보다 같지 않은지 불리언값 반환
np.not_equal(x,y)

array([[False, False, False],
       [ True,  True,  True]])

In [41]:
#x요소와 y2요소의 논리 AND 연산
np.logical_and([True, True, True, False],[False, False, False, False])

array([False, False, False, False])

In [42]:
#x요소와 y요소의 논리 OR 연산
np.logical_or([True, True, True, False],[False, False, False, False])


array([ True,  True,  True, False])

In [43]:
# x요소와 y요소의 논리 XOR 연산
>>> np.logical_xor([True, True, True, False],[False, False, False, False])


array([ True,  True,  True, False])