In [45]:
import numpy as np

def cal_sqrt(val):
    result = np.zeros(val.size)
#     print(result)
#     print(len(result))
   
    for i in range(len(val)):
#         print("i: ", val[i])
        result[i] = val[i] ** 2
    return result

# sample = np.random.rand(2_000_000)
sample = np.random.rand(5)
print(sample)
# print(len(sample))
# print(sample.size)
cal_sqrt(sample)


# sample2 = np.random.randint(1, 10, size=5)
# sample2


[0.84785536 0.11626245 0.79060304 0.5453358  0.56121508]


array([0.71885871, 0.01351696, 0.62505317, 0.29739114, 0.31496236])

In [46]:
print(sample ** 2)

[0.71885871 0.01351696 0.62505317 0.29739114 0.31496236]


In [3]:
import numpy as np

def cal_add(val1, val2):
  res = np.zeros(val1.shape)
  rows, cols = val1.shape

  for i in range(rows):
    for j in range(cols):
      res[i][j] = val1[i][j] + val2[i][j]

  return res

"""
파이썬에는 상수가 없다. 그래서 변수와 상수를 구분하기 위해,
변수는 소문자, 상수는 대문자로 구분해서 흔히 사용한다.
"""

ROWS = 1_000
COLS = 1_000
# ROWS = 5
# COLS = 50

sample1 = np.random.rand(ROWS,COLS)
sample2 = np.random.rand(ROWS,COLS)
#res = cal_add(sample1, sample2)
#res[:2]

In [2]:
%%timeit
cal_add(sample1, sample2)

608 ms ± 7.71 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [108]:
%timeit sample1 + sample2
res2

2.65 ms ± 46.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


array([[0.67838972, 1.05545376, 0.8497147 , ..., 0.76156043, 0.79991929,
        1.08201206],
       [1.55583623, 1.22002688, 1.01334548, ..., 0.64295518, 0.90606236,
        0.9019155 ],
       [1.30574252, 0.25325696, 1.59317459, ..., 0.60926406, 1.36939725,
        1.26221207],
       ...,
       [0.55880487, 0.45189853, 1.06399989, ..., 0.42908398, 1.22606307,
        0.42018882],
       [0.95233553, 1.27494398, 1.79304518, ..., 1.18940419, 1.35459346,
        0.66756583],
       [1.69273695, 1.54166567, 0.25832049, ..., 1.43513353, 1.4399375 ,
        1.5476677 ]])

In [106]:
res2 = sample1 + sample2
res2[:2]

array([[0.67838972, 1.05545376, 0.8497147 , ..., 0.76156043, 0.79991929,
        1.08201206],
       [1.55583623, 1.22002688, 1.01334548, ..., 0.64295518, 0.90606236,
        0.9019155 ]])

In [102]:
res.shape

(1000, 1000)

In [97]:
res2.shape

(1000, 1000)

In [109]:
res3 = np.add(sample1, sample2)

In [111]:
%load_ext memory_profiler


In [135]:
%memit cal_add(sample1, sample2)

peak memory: 235.55 MiB, increment: 6.84 MiB


In [115]:
%memit np.add(sample1, sample2)

peak memory: 227.97 MiB, increment: 0.00 MiB


In [116]:
np.around(res3)

array([[1., 1., 1., ..., 1., 1., 1.],
       [2., 1., 1., ..., 1., 1., 1.],
       [1., 0., 2., ..., 1., 1., 1.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 1., 2., ..., 1., 1., 1.],
       [2., 2., 0., ..., 1., 1., 2.]])

In [117]:
x = np.array([0.001, 2, 6])

display(np.log(x))

array([-6.90775528,  0.69314718,  1.79175947])

In [149]:
import numpy as np

# def cal_add(val1, val2):
#     res = np.zeros(val1.shape)
#     rows, cols = val1.shape

#     for i in range(rows):
#         for j in range(cols):
#             res[i][j] = val1[i][j] + val2[i][j]
   
#     return res

# """
# 파이썬에는 상수가 없다. 그래서 변수와 상수를 구분하기 위해,
# 변수는 소문자, 상수는 대문자로 구분해서 흔히 사용한다.
# """

ROWS = 1_000
COLS = 1_000

sample1 = np.random.randint(ROWS, size=ROWS*COLS, dtype=np.int64)
sample1 = sample1.reshape(ROWS, COLS)
# sample1[:1]
sample2 = np.random.randint(ROWS, size=ROWS*COLS, dtype=np.int64)
sample2 = sample1.reshape(ROWS, COLS)
# sample2 = np.random.rand(ROWS,COLS, dtype=np.int32)
res = cal_add(sample1, sample2)
res[:2]

array([[ 364., 1876., 1920., ...,  434., 1818., 1246.],
       [1346., 1410.,  748., ...,  502., 1202., 1068.]])

In [137]:
%%timeit
cal_add(sample1, sample2)

670 ms ± 7.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [150]:
%memit cal_add(sample1, sample2)

peak memory: 255.36 MiB, increment: 7.32 MiB


In [160]:
# import numpy as np

def cal_add(val1, val2):
    res = np.zeros(val1.shape)
    rows, cols = val1.shape

    for i in range(rows):
        for j in range(cols):
            res[i][j] = val1[i][j] + val2[i][j]
   
    return res

"""
파이썬에는 상수가 없다. 그래서 변수와 상수를 구분하기 위해,
변수는 소문자, 상수는 대문자로 구분해서 흔히 사용한다.
"""

ROWS = 1_000
COLS = 1_000

sample3 = np.random.randint(ROWS, size=ROWS*COLS, dtype=np.int16)
sample3 = sample3.reshape(ROWS, COLS)

sample4 = np.random.randint(ROWS, size=ROWS*COLS, dtype=np.int16)
sample4 = sample4.reshape(ROWS, COLS)
res2 = cal_add(sample3, sample4)
res2[:2]

array([[1491., 1116., 1088., ...,  426., 1311., 1047.],
       [1151., 1083.,  890., ..., 1842., 1773., 1148.]])

In [146]:
%%timeit
cal_add(sample3, sample4)

656 ms ± 4.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [161]:
%memit cal_add(sample3, sample4)

peak memory: 267.43 MiB, increment: 7.36 MiB
