In [3]:
import numpy as np
x = np.arange(1,7).reshape((2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 주어진 축에 따라 요소들의 합 구하기
np.sum(x) # = x.sum()


21

In [6]:
# 주어진 축에 따라 요소들의 산술 평균 구하기
np.mean(x) # = x.mean()


3.5

In [7]:
# 표준 편차 구하기
np.std(x)

1.707825127659933

In [9]:
# x배열 요소의 분산 구하기
np.var(x)


2.9166666666666665

In [8]:
# 주어진 축에 따라 요소들의 누적 합 구하기
np.cumsum(x) # = x.comsum()


array([ 1,  3,  6, 10, 15, 21])

In [10]:
# 주어진 축에 따라 배열 요소들의 누적 곱 구하기
np.cumprod(x)


array([  1,   2,   6,  24, 120, 720])

In [11]:
import numpy as np
#
np.random.rand(3,4)

array([[0.72290149, 0.14059965, 0.51491904, 0.07058613],
       [0.60287844, 0.11622451, 0.05789952, 0.58571584],
       [0.91426904, 0.74048133, 0.7370438 , 0.98684073]])

In [12]:
np.random.randint(4) # [0,4) 범위 난수 

0

In [13]:
np.random.randint(1,4) # [1,4) 범위 난수

2

In [14]:
np.random.randint(1,4, size=10) # [0,4) 범위 10개 난수

array([2, 2, 2, 1, 1, 2, 3, 2, 3, 3])

In [15]:
np.random.randn(2,3)

array([[ 0.96979667, -0.04481418, -0.83748229],
       [ 0.17619511, -0.73325208, -1.676025  ]])

In [16]:
np.random.seed(11)

In [17]:
np.random.standard_normal((2,3))

array([[ 1.74945474, -0.286073  , -0.48456513],
       [-2.65331856, -0.00828463, -0.31963136]])

In [18]:
np.random.normal(1,1,size=(3,3))

array([[ 0.46337064,  1.31540267,  1.42105072],
       [-0.06560298,  0.11376033,  0.52426651],
       [ 1.68968231,  1.56119218, -0.30554851]])

In [19]:
x = np.random.normal(1,1,size=(3,3))
x

array([[-0.11947526,  1.73683739,  2.57463407],
       [ 0.96892491,  0.31655337,  2.0956297 ],
       [ 0.69042336,  1.72575222,  2.54907163]])

In [20]:
# 각 행의 요소를 정렬
np.sort(x)

array([[-0.11947526,  1.73683739,  2.57463407],
       [ 0.31655337,  0.96892491,  2.0956297 ],
       [ 0.69042336,  1.72575222,  2.54907163]])

In [21]:
# 각 열의 요소를 정렬
np.sort(x, axis=0)


array([[-0.11947526,  0.31655337,  2.0956297 ],
       [ 0.69042336,  1.72575222,  2.54907163],
       [ 0.96892491,  1.73683739,  2.57463407]])

In [22]:
#역순으로 정렬
np.sort(x, axis=1)[::-1]


array([[ 0.69042336,  1.72575222,  2.54907163],
       [ 0.31655337,  0.96892491,  2.0956297 ],
       [-0.11947526,  1.73683739,  2.57463407]])

In [23]:
# 오름차순 정렬시의 인덱스
np.argsort(x)

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [26]:
import numpy as np
x1 = np.array([10, 20, 30, 10, 10])
y1 = np.array([40, 10, 10, 20, 30])
idx = np.lexsort((y1, x1))
idx

array([3, 4, 0, 1, 2], dtype=int64)

In [27]:
for i in idx:
    print(x1[i], y1[i])


10 20
10 30
10 40
20 10
30 10


In [31]:
x = [1,2,2,2,3,3,4,4,5,5,5,6]
y = [1,1,1,2,3,4,4,4,5,6,6,7,7]
np.unique(x)


array([1, 2, 3, 4, 5, 6])

In [32]:
np.union1d(x,y) #x, y 합집합을 구한 후, 고유값 반환 

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
np.intersect1d(x,y) #x, y 교집합을 구한 후, 고유값 반환

array([1, 2, 3, 4, 5, 6])

In [34]:
np.setdiff1d(y1, x1) #x의 y 차집합을 구한 후, 교유값 반환

array([7])

In [35]:
np.in1d(y,x) #x 요소가 y에 포함되는지 불리언 반환

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False])

In [36]:
import numpy as np
large_x = np.random.randint(0,10, size=1_000_000).reshape(1000,1000)
large_x.shape

(1000, 1000)

In [37]:
large_x[-2:]

array([[6, 4, 5, ..., 1, 1, 5],
       [0, 0, 3, ..., 3, 0, 5]])

In [38]:
# 텍스트파일로 저장, 구분자 ‘,’
np.savetxt('large_x.csv', large_x, delimiter=',')

In [39]:
# 텍스트파일을 불러오기, 구분자 ‘,’
x2=np.loadtxt('large_x.csv', delimiter=',')
x2.shape


(1000, 1000)

In [40]:
x2[-2:]

array([[6., 4., 5., ..., 1., 1., 5.],
       [0., 0., 3., ..., 3., 0., 5.]])

In [41]:
# 바이너리 파일로 저장해 보자.
np.save('large_x', large_x)
x3 = np.load('large_x.npy')
x3.shape


(1000, 1000)

In [42]:
x3[-2:]

array([[6, 4, 5, ..., 1, 1, 5],
       [0, 0, 3, ..., 3, 0, 5]])

In [43]:
# 압축 바이너리 파일로 저장
np.savez_compressed('large_x2', a=large_x)
loaded = np.load('large_x2.npz')
print(loaded["a"])


[[1 0 3 ... 3 7 5]
 [6 6 5 ... 9 8 6]
 [6 3 4 ... 1 1 1]
 ...
 [4 1 7 ... 4 9 0]
 [6 4 5 ... 1 1 5]
 [0 0 3 ... 3 0 5]]


In [44]:
large_x

array([[1, 0, 3, ..., 3, 7, 5],
       [6, 6, 5, ..., 9, 8, 6],
       [6, 3, 4, ..., 1, 1, 1],
       ...,
       [4, 1, 7, ..., 4, 9, 0],
       [6, 4, 5, ..., 1, 1, 5],
       [0, 0, 3, ..., 3, 0, 5]])

In [46]:
x2 = large_x.ravel()
x2

array([1, 0, 3, ..., 3, 0, 5])

In [47]:
x2.shape

(1000000,)

In [48]:
x3 = large_x.flatten() 
x3.shape


(1000000,)

In [50]:
x4 = large_x.reshape(-1) # -1를 주면 1차원 배열화됨
x4.shape

(1000000,)

## allclose 함수

In [18]:
allclose1 = [1, 1, 1/3, 2]
allclose2 = [1, 1, 1/3, 2]


allclose1 == allclose2


True

In [22]:
import numpy as np


allclose1 = [1, 1, 1/3, 2]
allclose2 = [0.9999999, 1.0, 0.33333, 2]

allclose1 == allclose2


False

In [13]:
print(allclose1[0] == allclose2[0])
print(allclose1[1] == allclose2[1])
print(allclose1[2] == allclose2[2])
print(allclose1[3] == allclose2[3])

False
True
False
True


In [28]:
np.allclose(allclose1, allclose2, rtol=1e-06)

False

In [29]:
np.allclose(allclose1, allclose2, rtol=1e-05)

True

In [27]:
np.allclose(allclose1, allclose2, rtol=1e-06)

False