# 이항 유니버설 함수

In [1]:
import numpy as np
x = np.arange(1,7).reshape((2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
y = np.arange(1,4)
y

array([1, 2, 3])

In [3]:
#add
x+y

array([[2, 4, 6],
       [5, 7, 9]])

In [4]:
#subtract
np.subtract(x,y)

array([[0, 0, 0],
       [3, 3, 3]])

In [5]:
x + np.negative(y)

array([[0, 0, 0],
       [3, 3, 3]])

In [6]:
# 곱하기
np.multiply(x,y)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [7]:
#나누기
np.divide(x, y)

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [8]:
#나눈 몫
np.floor_divide(x,y)

array([[1, 1, 1],
       [4, 2, 2]])

In [9]:
#x요소의 y요소 제곱
np.power(x,y)

array([[  1,   4,  27],
       [  4,  25, 216]])

In [10]:
#x요소을 y요소로 나눈 나머지
np.mod(x,y)

array([[0, 0, 0],
       [0, 1, 0]])

In [11]:
#x요소와 y요소의 최대공약수
np.gcd(x, y)

array([[1, 2, 3],
       [1, 1, 3]])

In [12]:
#x요소과 y 요소별 최대값. fmax는 NaN를 무시함
np.maximum([[1,2,3],[4,5,np.nan]], y)

array([[ 1.,  2.,  3.],
       [ 4.,  5., nan]])

In [13]:
np.fmax([[1,2,3],[4,5,np.nan]], y)

array([[1., 2., 3.],
       [4., 5., 3.]])

In [14]:
#x요소과 y 요소별 최소값. fmin은 NaN를 무시함
np.minimum([[1,2,3],[4,5,np.nan]], y)

array([[ 1.,  2.,  3.],
       [ 1.,  2., nan]])

In [15]:
np.fmin([[1,2,3],[4,5,np.nan]],y)

array([[1., 2., 3.],
       [1., 2., 3.]])

In [16]:
#x요소가 y요소보다 큰지 불리언 값 반환
np.greater(x,y)

array([[False, False, False],
       [ True,  True,  True]])

In [17]:
#x요소가 y요소보다 크거나 같은지 불리언값 반환
np.greater_equal(x,y)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [18]:
x >= y

array([[ True,  True,  True],
       [ True,  True,  True]])

In [19]:
#x요소가 y요소보다 작음
np.less(x,y)

array([[False, False, False],
       [False, False, False]])

In [20]:
x < y

array([[False, False, False],
       [False, False, False]])

In [21]:
#x요소가 y요소보다 작거나 같은지 불리언값 반환
np.less_equal(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [22]:
#x요소가 y요소와 같은지 불리언값 반환
np.equal(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [23]:
# x요소가 y요소보다 같지 않은지 불리언값 반환
np.not_equal(x,y)

array([[False, False, False],
       [ True,  True,  True]])

In [24]:
#x요소와 y요소의 논리 AND 연산
np.logical_and([True, True, True, False],[False, False, False, False])

array([False, False, False, False])

In [25]:
#x요소와 y요소의 논리 OR 연산
np.logical_or([True, True, True, False],[False, False, False, False])


array([ True,  True,  True, False])

In [26]:
# x요소와 y요소의 논리 XOR 연산
np.logical_xor([True, True, True, False],[False, False, False, False])


array([ True,  True,  True, False])