In [1]:
import numpy as np

a = np.random.rand(2,3)
b = np.random.rand(3,4)

a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,4) 

In [2]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b = np.array([0,1,2])
b


array([0, 1, 2])

In [6]:
c = a + b
c

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [10]:
d = a + 2
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
a_dash = np.array([[2,2,2],[2,2,2],[2,2,2]])

In [12]:
e = a + a_dash
e

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])