In [5]:
import numpy as np
large_x = np.random.randint(0,10, size=1_000_000).reshape(1000,1000)
large_x.shape

(1000, 1000)

In [9]:
large_x[-2:]

array([[8, 6, 9, ..., 5, 7, 3],
       [8, 2, 5, ..., 8, 8, 6]])

In [14]:
np.savetxt('large_x.csv', large_x, delimiter=',')

In [15]:
x2=np.loadtxt('large_x.csv', delimiter=',')

In [13]:
x2.shape

(1000, 1000)

In [16]:
x2[-2:]

array([[8., 6., 9., ..., 5., 7., 3.],
       [8., 2., 5., ..., 8., 8., 6.]])

# 바이너리 파일로 저장

In [17]:
np.save('large_x', large_x)

In [18]:
x3 = np.load('large_x.npy')

In [19]:
x3.shape

(1000, 1000)

In [20]:
x3[-2:]

array([[8, 6, 9, ..., 5, 7, 3],
       [8, 2, 5, ..., 8, 8, 6]])

# 압축 바이너리 파일로 저장

In [50]:
np.savez_compressed('large_x', a=large_x)

In [51]:
loaded = np.load('large_x.npz')
print(loaded["a"])

[[0 2 6 ... 7 0 4]
 [0 4 2 ... 9 8 0]
 [3 5 3 ... 1 8 1]
 ...
 [5 6 2 ... 9 4 0]
 [8 6 9 ... 5 7 3]
 [8 2 5 ... 8 8 6]]


In [41]:
# loaded['a']


AttributeError: 'NpzFile' object has no attribute 'shape'

# 평탄화해보기

In [60]:
large_x

array([[0, 2, 6, ..., 7, 0, 4],
       [0, 4, 2, ..., 9, 8, 0],
       [3, 5, 3, ..., 1, 8, 1],
       ...,
       [5, 6, 2, ..., 9, 4, 0],
       [8, 6, 9, ..., 5, 7, 3],
       [8, 2, 5, ..., 8, 8, 6]])

In [55]:
x2 = large_x.ravel()

array([0, 2, 6, ..., 8, 8, 6])

In [57]:
x2.shape

(1000, 1000)

In [58]:
x3 = large_x.flatten()
x3.shape

(1000000,)

In [59]:
x4 = large_x.reshape(-1)
x4.shape


(1000000,)

In [61]:
x2[0][0] = 11

In [62]:
x2

array([[11.,  2.,  6., ...,  7.,  0.,  4.],
       [ 0.,  4.,  2., ...,  9.,  8.,  0.],
       [ 3.,  5.,  3., ...,  1.,  8.,  1.],
       ...,
       [ 5.,  6.,  2., ...,  9.,  4.,  0.],
       [ 8.,  6.,  9., ...,  5.,  7.,  3.],
       [ 8.,  2.,  5., ...,  8.,  8.,  6.]])

In [63]:
large_x

array([[0, 2, 6, ..., 7, 0, 4],
       [0, 4, 2, ..., 9, 8, 0],
       [3, 5, 3, ..., 1, 8, 1],
       ...,
       [5, 6, 2, ..., 9, 4, 0],
       [8, 6, 9, ..., 5, 7, 3],
       [8, 2, 5, ..., 8, 8, 6]])

In [64]:
x2.shape

(1000, 1000)

In [67]:
arr1 = np.array("i", [1,2,3,4,5])
arr1

TypeError: Field elements must be 2- or 3-tuples, got '1'